apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node
  name: node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ngix
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: node
        name: node
